// Generate service worker code from manifest configuration.

const DefaultConfig = {
    version: '1.0',
    origins: [],
    plugins: [],
    cache: {
        static: []
    }
}

function makeSW( manifest ) {
    let {
        version,
        origins,
        plugins,
        cache 
    } = Object.assign( DefaultConfig, manifest.serviceWorker );

    return `// Auto-generated by Locomote.sh / ${new Date()}
self.importScripts(${makeImports( version, plugins )});
${makeAddOrigins( origins )}
${makeCacheStatements( cache )}
`;
}

const CDNURL = 'https://locomote.sh/cdn/sw/';

const PluginURLs = {
    '__core': ver => `${CDNURL}${ver}/locomote-sw.js`,
    'search': ver => `${CDNURL}${ver}/locomote-search.js`
}

function makeImports( version, plugins ) {
    plugins.unshift('__core');
    plugins = plugins.map( ref => {
        let url = PluginURLs[ref];
        return url ? url( version ) : ref;
    });
    return formatJSStringArray( plugins );
}

function makeAddOrigins( origins ) {
    if( origins.length == 0 ) {
        return '';
    }
    return `self.addOrigins([${formatJSStringArray( origins )}]);`;
}

function makeCacheStatements( cache ) {
    let { static } = cache;
    if( !(static && static.length) ) {
        return '';
    }
    return `self.staticCache([${formatJSStringArray( static )}]);`;
}

function formatJSStringArray( array ) {
    return `"${array.join('",\n\t"')}"`;
}

let manifest = require('./locomote.json');
console.log( makeSW( manifest ) );
